### ISSUE TITLE
auth_success.py not found

### ISSUE THREAD

**Issue by SambariManikanta09** [dr490n1s3d-3d8/Major_Project#2]
Hello, actually check your project for my college mini project work wanted to test it and develop a similar application. 

`\dr490n1s3d-3d8\Major_Project\auth.py", line 141,
 import auth_success
ModuleNotFoundError: No module named 'auth_success'`

Can you please help me resolve this issue It would be a great help understanding the project and login system

**Comment by primordialhuman** [comment]
Sorry for the late reply

I will check it and update the readme file
